### PR TITLE
Added save imaga option

### PR DESCRIPTION
**Pull request by Michael36500**

### CODE REVIEW

**Review by MisansProducts — APPROVED** [review]
Wow. This is an amazing feature to add. I have never considered creating images with programs because I thought it was a tedious process. You proved me wrong. This will inspire to me to mess with that cv2 library to make pictures.

Since your addition creates new files, I will have to add a .gitignore file to not upload those files to GitHub. The `sudokuboard.png` is an exception since it is a template. I will also remove the `sudoku_hidden.png` file because it does not appear to do anything. I will also remove the `print(line)` in your `save_board.py` because I think it was there for you to debug it. Finally, I will add some error handling with your new input prompts and update the README file to include the required cv2 library installation.

**Comment by Michael36500** [comment]
You are so sweet. I forget to remove print(line), and also I didn't know what .gitignore do, so thanks for your help.

**Comment by Michael36500** [comment]
You are so sweet. I forget to remove print(line), and also I didn't know what .gitignore do, so thanks for your help. And sudoku_hidden.png and sudoku_full.png are resolves...
If you would want, I can help a bit with opencv.

**Comment by MisansProducts** [comment]
> You are so sweet. I forget to remove print(line), and also I didn't know what .gitignore do, so thanks for your help. And sudoku_hidden.png and sudoku_full.png are resolves... If you would want, I can help a bit with opencv.

Ah I see, and thank you. Yes, I would like your help with opencv if you can show me the ropes and all.

**Pull request merged**
